<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoSingleReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoSingleReferenceRepository extends EntityRepository
{
}
